name: dataScience
channels:
  - defaults
dependencies:
  - pandas
  - notebook
  - numpy
  - python=3.9
  - scikit-learn
  - jupyter
  - matplotlib
  - statsmodels
  - sktime-all-extras
  - py-xgboost
